services:
  availablityio:
    container_name: availablityio
    image: hossman39/availablityio
    ports:
      - "7874:7874"
    environment:
      - TMDB_API_KEY=(your_tmdb_api_key_here)
      - PORT=7874
    restart: unless-stopped